// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/physiosync/AppointmentCard.tsx": () => import("../components/mockups/physiosync/AppointmentCard.tsx"),
  "./components/mockups/physiosync/OfflineBanner.tsx": () => import("../components/mockups/physiosync/OfflineBanner.tsx"),
  "./components/mockups/physiosync/SidebarSync.tsx": () => import("../components/mockups/physiosync/SidebarSync.tsx")
};
